config/routes.rb
MediaBlog::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  ActiveAdmin.routes(self)

  resources :reports
  get 'reports/slug_suggestion/:title' => 'reports#slug_suggestion', as: :slug_suggestion

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, Report
      can :manage, Report, user_id: user.id
    end
  end
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability

  def initialize(user)
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user ||= User.new
    can :manage, :all if user.admin?
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :reports, dependent: :restrict_with_exception

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :report

  has_attached_file(
    :file,
    styles: { medium: '400x400>', thumb: '100x100#' },
    path: ':class/:attachment/:id_partition/:style/:hash.:extension',
    url: ':class/:attachment/:id_partition/:style/:hash.:extension',
    hash_secret: '9494nfjwqpofkadfa9fa093e4',
    storage: :dropbox,
    dropbox_credentials: Rails.root.join('config/dropbox.yml')
  )

  validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/
  validates_attachment_file_name :file, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
end

app/models/report.rb
class Report < ActiveRecord::Base
  MAX_PICTURES = 5

  belongs_to :category
  belongs_to :user
  has_many :pictures

  validates :title, :body, :category, :user, :slug, presence: true
  validates :slug, uniqueness: true
  validate :valid_number_of_pictures

  accepts_nested_attributes_for :pictures, allow_destroy: true, reject_if: :invalid_picture?

  alias_method :owner, :user
  alias_method :owner=, :user=

  def slug_suggestion
    slug = title.downcase.gsub(/\s+/, '_')
    slug if !Report.where(slug: slug).first
  end

  private

  def invalid_picture?(attributes)
    attributes['file'].blank? && attributes['id'].blank?
  end

  def valid_number_of_pictures
    if pictures.size > MAX_PICTURES
      errors.add(:pictures, "are more than alowed. Maximum #{MAX_PICTURES} are allowed")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reports

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  def name
    email
  end

  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    access_denied(exception)
  end

  def access_denied(exception)
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :create_report, only: [:create]
  load_and_authorize_resource

  before_action :set_categories, only: [:new, :edit, :create, :update]

  # GET /reports
  # GET /reports.json
  def index
    @reports = @reports.includes(:user)
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report.owner = current_user

    respond_to do |format|
      if @report.save
        format.html { redirect_to :reports, notice: 'Report was successfully created.' }
        format.json { render 'show', status: :created, location: @report }
      else
        format.html { render 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  # GET /report/slug_suggestion/:title
  def slug_suggestion
    @report = Report.new(title: params[:title])
    slug = @report.slug_suggestion
    render json: {slug: slug}
  end

  private

  def set_categories
    @categories = Category.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit(
      :title,
      :body,
      :slug,
      :category_id,
      pictures_attributes: [:id, :title, :file, :_destroy]
    )
  end

  def create_report
    @report = Report.new(report_params)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
    <div><%= render 'layouts/welcome' %></div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
  <%= link_to 'Reports', reports_path, class: 'navbar-brand' %>
</li>

app/views/layouts/_welcome.erb
<% if user_signed_in? %>
  <%= content_tag :span, current_user.email, class: 'email' %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Log in', new_user_session_path %>
  <%= link_to "Log in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Media Blog" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Media Blog" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller.controller_name.dasherize %> <%= controller.action_name.dasherize %>">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_for(report, html: { class: 'simple-form report' } ) do |f| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %>
    <span class="slug-suggestion"
        data-url="<%= slug_suggestion_url title: '-title-', format: :json %>">
      suggestion: <span class="suggestion"></span>
      <a href="#use">use</a>
    </span>
    <br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, categories, :id, :name, prompt: '-- Select --' %>
  </div>
  <ul class="report-pictures media-list">
    <%= f.fields_for :pictures do |picture_field| %>
      <%= render 'picture_item', f: picture_field, html_class: 'section' %>
    <% end %>
    <%= f.fields_for :pictures, Picture.new, child_index: '--replace--' do |picture_template| %>
      <%= render 'picture_item', f: picture_template, html_class: 'template' %>
    <% end %>
  </ul>
  <% if report.pictures.size < Report::MAX_PICTURES %>
    <%= button_tag 'Add Picture', type: 'button', class: 'add-picture',
                    data: {
                      'replace-pattern' => '--replace--',
                      'max-items' => Report::MAX_PICTURES
                    }
    %>
  <% end %>
  <div class="clear"></div>
  <div class="actions">
    <%= f.submit class: 'submit' %>
  </div>
<% end %>

app/views/reports/_picture_item.erb
<li class="<%= html_class %>" >
  <%= f.label :title %>
  <%= f.text_field :title %>
  <% if !f.object.new_record? %>
    <%= image_tag f.object.file.url(:thumb) %>
    <%= f.check_box :_destroy %>
    <%= f.label :_destroy, 'Remove' %>
  <% end %>
  <%= f.file_field :file %>
</li>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form', report: @report, categories: @categories %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Owner</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.title %></td>
        <td><%= report.slug %></td>
        <td><%= report.owner.email %></td>
        <td>
          <%= link_to 'Show', report, class: 'btn-show' if can? :read, report %>
          <%= link_to 'Edit', edit_report_path(report), class: 'btn-edit' if can? :edit, report %>
          <%= link_to 'Destroy', report, method: :delete, class: 'btn-destroy', data: { confirm: 'Are you sure?' } if can? :destroy, report %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path, class: 'btn btn-link' if can? :create, Report %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form', report: @report, categories: @categories %>

<%= link_to 'Back', reports_path, class: 'btn btn-link' %>

app/views/reports/show.html.erb
<h1>
  <%= @report.title %>
</h1>
<p>
  <%= @report.owner.email %>
</p>
<p>
  <% @report.pictures.each do |picture| %>
    <%= image_tag picture.file.url(:medium) %>
  <% end %>
</p>
<p>
  <%= @report.body %>
</p>

<%= link_to 'Edit', edit_report_path(@report), class: 'btn btn-link' if can? :edit, @report %> |
<%= link_to 'Back', reports_path, class: 'btn btn-link' %>

app/views/welcome/index.html.erb
<h2>Hi</h2>
<p>
  The time is now: <%= Time.now %>
</p>